package main

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strconv"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

// MaxParallelism returns the max GOMAXPROCS value, by comparing runtime.GOMAXPROCS
// with number of CPUs, and returning larger value
func MaxParallelism() int {
	maxProcs := runtime.GOMAXPROCS(0)
	numCPU := runtime.NumCPU()
	if maxProcs < numCPU {
		return maxProcs
	}
	return numCPU
}

// Ping will executes the ping of the websites.
//Input: website, channel
//Output: Ping results are sent to channel
func ping(website string, resultschannel chan []string) {
	//Check to make sure website is valid
	if website == "" {
		return
	}

	//Communicate with user
	fmt.Printf("Thank you! ~~%s~~ is now being sent packets! Please wait for results.\n", website)

	//Assign the arguments
	arg1 := "ping"
	arg2 := website
	arg3 := "-c 3"
	arg4 := "-q"

	//Ping the websites using the command line
	cmd := exec.Command(arg1, arg2, arg3, arg4)
	stdout, err := cmd.Output()

	//Check for request timeout
	if strings.Contains(string(stdout), "100.0%") {
		resultschannel <- []string{website + " received no packets.", "--", "--", "--", "--"}
		return
	}
	//Check for errors
	if err != nil {
		fmt.Println(err)
		if err.Error() == "exit status 68" {
			resultschannel <- []string{website + " is not available.", "--", "--", "--", "--"}
		}
		return
	}

	stdoutnew := string(stdout)
	valuesum := strings.Split(stdoutnew, "= ")[1]
	splitvalues := strings.Split(valuesum, "/")
	newstddev := strings.Split(splitvalues[3], " ms")[0]
	min, avg, max, stddev := splitvalues[0], splitvalues[1], splitvalues[2], newstddev
	webinfo := []string{website, min, avg, max, stddev}
	resultschannel <- webinfo

}

// Pinger executes the ping command sends stats to current channel
func Pinger(gmp int, websites []string) {
	runtime.GOMAXPROCS(gmp)
	resultschannel := make(chan []string)
	webinfocollection := [][]string{}

	//For each valid website entered, ping the website, send/receive the data to/from the channel, save the data for later output
	for i := range websites {
		if websites[i] != "" {
			go ping(websites[i], resultschannel)
			webinfo := <-resultschannel
			webinfocollection = append(webinfocollection, webinfo)
		}
	}

	//Create a table with the output data
	w := new(tabwriter.Writer)
	w.Init(os.Stdout, 8, 8, 3, '\t', 0)
	fmt.Fprintln(w, "\t")
	fmt.Fprintln(w, "WEBSITE\t MIN\t AVG\t MAX\t STDDEV\t")
	fmt.Fprintln(w, "-------\t -------\t -------\t -------\t -------\t")
	for i := range webinfocollection {
		fmt.Fprintln(w, webinfocollection[i][0], "\t", webinfocollection[i][1], "\t", webinfocollection[i][2], "\t", webinfocollection[i][3], "\t", webinfocollection[i][4], "\t")
	}
	fmt.Fprintln(w, "\t")
	w.Flush()
}

// Plot is a function to plot the statistics of GOMAXPROCS vs program run time
func plot(gmpToRuntime map[int]int64) {
	var keys []string
	var values []opts.BarData
	for keyvalue := 0; keyvalue < len(gmpToRuntime); keyvalue++ {
		fmt.Println("Key:", keyvalue, "=>", "Element:", gmpToRuntime[keyvalue])
		keystring := strconv.Itoa(keyvalue)
		keys = append(keys, keystring)
		values = append(values, opts.BarData{Value: gmpToRuntime[keyvalue]})
	}

	newbar := charts.NewBar()
	// set some global options like Title/Legend/ToolTip or anything else
	newbar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "GOMAXPROCS vs. PROGRAM RUN TIME",
		Subtitle: "Automatically Generated by Zhiyuan Huang, Asher Kang, & Maria Ringes",
	}))

	// Put data into instance
	newbar.SetXAxis(keys)
	newbar.AddSeries("Category A", values)
	// Where the magic happens
	f, _ := os.Create("bar.html")
	newbar.Render(f)

}

// Sets the GOMAXPROCS value, and parallelizes ping command while increasing GOMAXPROCS value by one
// in each thread.
func main() {
	var gmpToRuntime = make(map[int]int64) // Create an int slice to map GOMAXPROCS values to runtime in nanoseconds.

	gmp := MaxParallelism() // Set the max GOMAXPROCS value

	//Initializing necessary variables
	var input string
	var inputsplice []string

	//Saving desired websites from a user to variables
	fmt.Printf("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n")
	fmt.Printf("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n")
	fmt.Printf("Please enter the websites you would like to ping; each separated with a space. Otherwise, enter 'q' to quit! ")
	in := bufio.NewReader(os.Stdin)
	input, _ = in.ReadString('\n')
	input = strings.TrimSuffix(input, "\n")
	inputsplice = strings.Split(input, " ")

	// Iterate through every possible value of GOMAXPROCS and run Pinger program.
	// Return the runtime of each iteration.
	for i := 0; i < gmp+1; i++ {
		fmt.Printf("\n\n- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n")
		fmt.Printf("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n")
		fmt.Printf("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n")
		fmt.Printf("Iteration %d\n", i)
		start := time.Now()
		Pinger(i, inputsplice)
		duration := time.Since(start)
		gmpToRuntime[i] = duration.Nanoseconds()
	}

	// Print out the final map of GOMAXPROCS values to program runtimes
	fmt.Printf("Time map is: \n")
	fmt.Println(gmpToRuntime)

	//Plot gmpToRunTime -> Output Graph
	plot(gmpToRuntime)

}
